################################# Default configuration ###################
baseURL = "http://oxyseas.rbind.io"
title = "Students for Equity and Advocacy in STEM"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo2.png"
logo_width = "150px"
# Meta data
description = "We are a student-led group striving for just and equitable learning environments for historically underrepresented* students.The purpose of Students for Equity & Advocacy in STEM (SEAS) is to support and empower students from all backgrounds and class years, especially those from marginalized or historically underrepresented* communities in Science. We are united in our effort to foster an intentional and accessible space for students from diverse backgrounds to build community and a sense of belonging within academia. We are  committed to advocating for the needs of marginalized students and for a social justice-centered curriculum. We also aim to collaborate with faculty and alumni to elevate accessibility to resources and opportunities that will support marginalized students’ educational, professional, and personal goals. *includes BIPOC students, first-generation students, low-income students, disabled students, and LGBTQ+ students."

author = "Themefisher"
# Contact Information
# mobile = ""
email = "seas[at]oxy.edu"
location = "Los Angeles, CA, USA"
# contact form action
contact_form_action = "https://formspree.io/f/xjvpjwed" # contact form works with : https://formspree.io
# Google Analitycs
google_analytics_id = "G-L7G5H5YES9" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Discover Our Projects"
link = "projects"

# google map
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "34.1273"
map_longitude = "-118.2101"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
# [[params.social]]
# icon = "ion-social-google-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "https://drive.google.com/drive/u/0/folders/0ALvoowozSzh9Uk9PVA"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/oxy_seas/?hl=en"

# [[params.social]]
# icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

# [[params.social]]
# icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Projects"
URL = "projects"
weight = 3
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Projects"
  name = "CATALYST"
  URL = "catalyst"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Projects"
  name = "PROMISE"
  URL = "promise"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "Projects"
  name = "BEARs"
  URL = "bears"
  weight = 3
  
[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 4


# footer menu
[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "CATALYST"
URL = "catalyst"
weight = 1

[[Languages.en.menu.footer]]
name = "PROMISE"
URL = "promise"
weight = 2

[[Languages.en.menu.footer]]
name = "BEARs"
URL = "bears"
weight = 3

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 3




